// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9yN3pGwAh9CWVe2LXGsETn
// Component: bRQSjf8wyRdv

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useScreenVariants as useScreenVariantsoyx73T20ZbVx } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Oyx73t20ZbVx/globalVariant
import { ThemeValue, useTheme } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: B67dTyYcNNXN/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 9yN3pGwAh9CWVe2LXGsETn/projectcss
import sty from "./PlasmicSection8.module.css"; // plasmic-import: bRQSjf8wyRdv/css

createPlasmicElementProxy;

export type PlasmicSection8__VariantMembers = {};
export type PlasmicSection8__VariantsArgs = {};
type VariantPropType = keyof PlasmicSection8__VariantsArgs;
export const PlasmicSection8__VariantProps = new Array<VariantPropType>();

export type PlasmicSection8__ArgsType = {};
type ArgPropType = keyof PlasmicSection8__ArgsType;
export const PlasmicSection8__ArgProps = new Array<ArgPropType>();

export type PlasmicSection8__OverridesType = {
  section8?: Flex__<"section">;
  columns?: Flex__<"div">;
  avtarContent?: Flex__<"div">;
  h2?: Flex__<"h2">;
  avatarImage?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
};

export interface DefaultSection8Props {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSection8__RenderFunc(props: {
  variants: PlasmicSection8__VariantsArgs;
  args: PlasmicSection8__ArgsType;
  overrides: PlasmicSection8__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsoyx73T20ZbVx(),
    theme: useTheme()
  });

  return (
    <section
      data-plasmic-name={"section8"}
      data-plasmic-override={overrides.section8}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.section8,
        {
          [projectcss.global_theme_darkGrayscale]: hasVariant(
            globalVariants,
            "theme",
            "darkGrayscale"
          ),
          [projectcss.global_theme_dark]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),
          [projectcss.global_theme_grayscale]: hasVariant(
            globalVariants,
            "theme",
            "grayscale"
          )
        }
      )}
    >
      <div
        data-plasmic-name={"columns"}
        data-plasmic-override={overrides.columns}
        className={classNames(projectcss.all, sty.columns)}
      >
        <div className={classNames(projectcss.all, sty.column__ptNN)}>
          <div
            data-plasmic-name={"avtarContent"}
            data-plasmic-override={overrides.avtarContent}
            className={classNames(projectcss.all, sty.avtarContent)}
          >
            <h2
              data-plasmic-name={"h2"}
              data-plasmic-override={overrides.h2}
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2
              )}
            >
              {"About the instructor"}
            </h2>
            <p
              className={classNames(
                projectcss.all,
                projectcss.p,
                projectcss.__wab_text,
                sty.p__gd1AS
              )}
            >
              {"Jane Doe, Title"}
            </p>
            <p
              className={classNames(
                projectcss.all,
                projectcss.p,
                projectcss.__wab_text,
                sty.p__eDHqr
              )}
            >
              {
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
              }
            </p>
            <p
              className={classNames(
                projectcss.all,
                projectcss.p,
                projectcss.__wab_text,
                sty.p__d1DMs
              )}
            >
              {
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
              }
            </p>
            <p
              className={classNames(
                projectcss.all,
                projectcss.p,
                projectcss.__wab_text,
                sty.p__xdXzC
              )}
            >
              {
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
              }
            </p>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.column___8Aq8G)}>
          <div
            data-plasmic-name={"avatarImage"}
            data-plasmic-override={overrides.avatarImage}
            className={classNames(projectcss.all, sty.avatarImage)}
          >
            <PlasmicImg__
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "100%"
                  : "auto"
              }
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "400px"
                  : "auto"
              }
              loading={"lazy"}
              src={{
                src: "/plasmic/theme_switcher/images/image4.png",
                fullWidth: 930,
                fullHeight: 1162,
                aspectRatio: undefined
              }}
            />
          </div>
        </div>
      </div>
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  section8: ["section8", "columns", "avtarContent", "h2", "avatarImage", "img"],
  columns: ["columns", "avtarContent", "h2", "avatarImage", "img"],
  avtarContent: ["avtarContent", "h2"],
  h2: ["h2"],
  avatarImage: ["avatarImage", "img"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  section8: "section";
  columns: "div";
  avtarContent: "div";
  h2: "h2";
  avatarImage: "div";
  img: typeof PlasmicImg__;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSection8__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSection8__VariantsArgs;
    args?: PlasmicSection8__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSection8__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSection8__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSection8__ArgProps,
          internalVariantPropNames: PlasmicSection8__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSection8__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "section8") {
    func.displayName = "PlasmicSection8";
  } else {
    func.displayName = `PlasmicSection8.${nodeName}`;
  }
  return func;
}

export const PlasmicSection8 = Object.assign(
  // Top-level PlasmicSection8 renders the root element
  makeNodeComponent("section8"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),
    avtarContent: makeNodeComponent("avtarContent"),
    h2: makeNodeComponent("h2"),
    avatarImage: makeNodeComponent("avatarImage"),
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicSection8
    internalVariantProps: PlasmicSection8__VariantProps,
    internalArgProps: PlasmicSection8__ArgProps
  }
);

export default PlasmicSection8;
/* prettier-ignore-end */
